openapi: 3.0.0
info:
  title: Sample API
  description: A simple example API to demonstrate OpenAPI structure.
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: https://staging-api.example.com/v1
    description: Staging server
paths:
  /users:
    get:
      summary: Get a list of users
      description: Retrieve a list of all registered users.
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: John Doe
                    email:
                      type: string
                      example: john.doe@example.com
    post:
      summary: Create a new user
      description: Add a new user to the system.
      requestBody:
        description: User object to create
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Jane Doe
                email:
                  type: string
                  example: jane.doe@example.com
      responses:
        "201":
          description: User created successfully
  /users/{id}:
    get:
      summary: Get a user by ID
      description: Retrieve a specific user by their unique ID.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the user
          schema:
            type: integer
      responses:
        "200":
          description: User found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: John Doe
                  email:
                    type: string
                    example: john.doe@example.com
        "404":
          description: User not found
